"""Predecessor catalog term lists for Cycle #30 domain reconciliation."""

from __future__ import annotations

W06_DOMAINS = (
    ("DOM-001", "games/schedules/scores"),
    ("DOM-002", "play-by-play"),
    ("DOM-003", "drives"),
    ("DOM-004", "team statistics"),
    ("DOM-005", "advanced team efficiency"),
    ("DOM-006", "player statistics"),
    ("DOM-007", "play participants"),
    ("DOM-008", "snap counts/participation"),
    ("DOM-009", "rosters"),
    ("DOM-010", "starters/depth charts"),
    ("DOM-011", "injuries/availability current"),
    ("DOM-012", "injuries/availability historical"),
    ("DOM-013", "recruiting"),
    ("DOM-014", "transfers"),
    ("DOM-015", "freshman/prospect priors"),
    ("DOM-016", "NFL draft outcomes"),
    ("DOM-017", "preseason honors/watch lists"),
    ("DOM-018", "head coaches/coordinators"),
    ("DOM-019", "assistant coaches/role histories"),
    ("DOM-020", "scheme/style/tendencies"),
    ("DOM-021", "program resources/finance"),
    ("DOM-022", "NIL/revenue-sharing regulatory context"),
    ("DOM-023", "historical issued weather forecasts"),
    ("DOM-024", "observed weather"),
    ("DOM-025", "venue coordinates/elevation"),
    ("DOM-026", "timezone/body clock"),
    ("DOM-027", "travel distance"),
    ("DOM-028", "home-field/venue effect"),
    ("DOM-029", "possession/tempo"),
    ("DOM-030", "field position/hidden yards"),
    ("DOM-031", "special teams"),
    ("DOM-032", "fourth-down decisions"),
    ("DOM-033", "clock management"),
    ("DOM-034", "garbage time/score state"),
    ("DOM-035", "opponent adjustment"),
    ("DOM-036", "schedule stress/workload"),
    ("DOM-037", "poll rankings"),
    ("DOM-038", "external ratings"),
    ("DOM-039", "markets"),
    ("DOM-040", "officials/crew history"),
    ("DOM-041", "officials upcoming assignments"),
    ("DOM-042", "playing rule era"),
    ("DOM-043", "eligibility/roster/transfer regulatory era"),
    ("DOM-044", "game stakes/CFP state"),
    ("DOM-045", "rivalry/homecoming/senior day"),
    ("DOM-046", "FCS strength"),
    ("DOM-047", "DII/DIII strength"),
    ("DOM-048", "NAIA strength"),
    ("DOM-049", "JUCO strength"),
    ("DOM-050", "live/in-game"),
    ("DOM-051", "advanced formation/personnel/tracking"),
    ("DOM-052", "licensing/redistribution metadata"),
)

C28_DOMAINS = (
    "schedules_results",
    "identities",
    "conferences",
    "rankings",
    "priors",
    "venues",
    "weather",
    "market",
    "rosters",
    "availability_injuries",
    "recruiting",
    "transfers",
    "head_coaches",
    "offensive_coordinator",
    "defensive_coordinator",
    "special_teams",
    "play_callers",
    "staff_regimes",
    "box_scores",
    "plays",
    "drives",
    "travel_rest_time_zone",
    "officials_penalties",
    "film",
    "calibration_ood_uncertainty",
    "total_team_score",
    "peer_cohorts",
    "am_archive",
    "bas_residual",
    "data_rights",
    "security",
    "costs",
    "governance",
)

SOURCE_POLICY_DOMAINS = (
    "schedules_results",
    "identities",
    "conferences",
    "rankings",
    "priors",
    "venues",
    "weather",
    "market",
    "rosters",
    "availability_injuries",
    "recruiting",
    "transfers",
    "head_coaches",
    "box_scores",
    "plays",
    "drives",
)

PIT_DOMAINS = (
    "team_outcome_priors",
    "rankings",
    "venues",
    "team_season_context",
    "plays",
    "drives",
    "team_box_scores",
    "player_box_scores",
    "advanced_game_statistics",
    "roster_membership",
    "structured_gamebook_equivalent",
    "provider_pregame_elo",
    "tamu_official_structured_archive",
    "weather_forecast_vintages",
    "pregame_availability",
    "recruiting_talent",
    "coaching_staff",
    "market_context",
)

CURRENT_REQUIREMENTS = (
    ("CURRENT-TOTAL-TEAM-SCORE", "total and team-score distributions"),
    ("CURRENT-CALIBRATION-OOD", "calibration, tail, and OOD uncertainty"),
    (
        "CURRENT-BAS-INFERENCE",
        "BAS residual inference distinct from opponent adjustment",
    ),
    ("CURRENT-PEER-COHORTS", "peer cohort construction"),
    ("CURRENT-REST", "rest and sequence"),
    ("CURRENT-TIMEZONE", "timezone and body clock"),
    ("CURRENT-TRAVEL", "per-team origin-to-venue travel"),
    ("CURRENT-HFA", "ordinary home-field exposure"),
    ("CURRENT-NEUTRAL", "neutral/site classification"),
    ("CURRENT-AVAILABILITY", "public availability reports"),
)
