"""R36-02: regenerate the file manifest t

hrough the canonical generator.

MR35R-01 lists 31 hosted findings at ``acedc690``: twenty stale size/hash
rows for ten files, ten files absent from the manifest entirely, and one
commit whose ``[process]`` subject touched material paths. None of them is
repaired by editing the manifest or relaxing the rule. The manifest is
regenerated by ``tools.repo_integrity.write_manifest`` -- the same function
``tools/packaging.py`` uses to build a release -- and the classification is
corrected through the policy's own
``historical_integration_corrections`` mechanism, SHA-scoped, with no
force-push and no rule disabled.

This tool prints the findings before and after so the repair is visible as a
difference rather than asserted.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from tools.repo_integrity import (  # noqa: E402
    tree_fingerprint,
    validate_manifest,
    write_manifest,
)
from tools.validate_execution_focus import validate as validate_execution_focus


class _bas_atomic:  # U37-11: atomic writes once this tool has imported the package itself
    @staticmethod
    def _module():
        import sys as _bas_sys

        if "aggie_analytics" not in _bas_sys.modules:
            return None  # never bind the package from another tree before the tool does
        try:
            from aggie_analytics import atomic_io
        except ImportError:
            return None
        return atomic_io

    @classmethod
    def write_text(cls, path, *args, **kwargs):
        module = cls._module()
        return module.write_text(path, *args, **kwargs) if module else path.write_text(*args, **kwargs)

    @classmethod
    def write_bytes(cls, path, *args, **kwargs):
        module = cls._module()
        return module.write_bytes(path, *args, **kwargs) if module else path.write_bytes(*args, **kwargs)

    @classmethod
    def open_write(cls, path, *args, **kwargs):
        module = cls._module()
        return module.open_write(path, *args, **kwargs) if module else path.open(*args, **kwargs)  # noqa: E402


def findings_as_rows(findings) -> list[dict[str, str]]:
    return [
        {"kind": f.kind, "path": f.path, "detail": f.detail} for f in findings
    ]


def git(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(root), *args],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return completed.stdout.strip()


def build(repo_root: Path, out_dir: Path, regenerate: bool) -> dict[str, Any]:
    before = findings_as_rows(validate_manifest(repo_root))
    focus_before = list(validate_execution_focus(repo_root))
    fingerprint_before = None
    rows = []
    if regenerate:
        rows, fingerprint_before = write_manifest(repo_root)
    after = findings_as_rows(validate_manifest(repo_root))
    focus_after = list(validate_execution_focus(repo_root))

    artifact = {
        "artifact_type": "CYCLE36_REPOSITORY_INTEGRITY_REPAIR",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "repo_root": str(repo_root),
        "head": git(repo_root, "rev-parse", "HEAD"),
        "tree": git(repo_root, "rev-parse", "HEAD^{tree}"),
        "branch": git(repo_root, "rev-parse", "--abbrev-ref", "HEAD"),
        "regenerated": regenerate,
        "generator": "tools.repo_integrity.write_manifest",
        "manifest_rows": len(rows) if regenerate else None,
        "tree_fingerprint": fingerprint_before,
        "manifest_findings_before": before,
        "manifest_findings_after": after,
        "manifest_finding_count_before": len(before),
        "manifest_finding_count_after": len(after),
        "execution_focus_findings_before": focus_before,
        "execution_focus_findings_after": focus_after,
        "execution_focus_note": (
            "Findings listed here come from a FULL-history local run. Hosted "
            "pull-request checks enforce changed-path classification only for "
            "commits unique to the PR branch, so immutable mainline commits "
            "appear locally and not in CI. The one PR-unique finding at "
            "acedc690 was 7156a6f73aca80ee6c6101fb47d23d0cf4c92f87 and is "
            "corrected SHA-scoped in the policy."
        ),
        "not_done": (
            "No history was rewritten, no branch was force-pushed and no "
            "validator rule was disabled or bypassed."
        ),
    }
    out_dir.mkdir(parents=True, exist_ok=True)
    _bas_atomic.write_text(out_dir / "CYCLE36_REPOSITORY_INTEGRITY.json", 
        json.dumps(artifact, indent=2, sort_keys=True), encoding="utf-8"
    )
    return artifact


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo-root", type=Path, default=ROOT)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument(
        "--check-only",
        action="store_true",
        help="Report findings without regenerating the manifest.",
    )
    args = parser.parse_args()
    artifact = build(
        args.repo_root.resolve(), args.out_dir, regenerate=not args.check_only
    )
    print(
        json.dumps(
            {
                "head": artifact["head"],
                "manifest_findings_before": artifact["manifest_finding_count_before"],
                "manifest_findings_after": artifact["manifest_finding_count_after"],
                "execution_focus_before": len(artifact["execution_focus_findings_before"]),
                "execution_focus_after": len(artifact["execution_focus_findings_after"]),
                "manifest_rows": artifact["manifest_rows"],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
